-- MySQL Script generated by MySQL Workbench
-- 11/16/21 16:50:14
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paises` (
  `idPais` SMALLINT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`idPais`),
  UNIQUE INDEX `idPais_UNIQUE` (`idPais` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleado` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido1` VARCHAR(30) NOT NULL,
  `apellido2` VARCHAR(30) NOT NULL,
  `identificacion` VARCHAR(30) NOT NULL,
  `idPais` SMALLINT NOT NULL,
  `borrado` BIT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `idEmpleado_UNIQUE` (`idEmpleado` ASC),
  INDEX `fk_Empleados_Paises_idx` (`idPais` ASC),
  CONSTRAINT `fk_Empleados_Paises`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursales` (
  `idSucursal` SMALLINT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idPais` SMALLINT NULL,
  `borrado` BIT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  UNIQUE INDEX `idSucursal_UNIQUE` (`idSucursal` ASC),
  INDEX `fk_Sucursales_Paises1_idx` (`idPais` ASC),
  CONSTRAINT `fk_Sucursales_Paises`
    FOREIGN KEY (`idPais`)
    REFERENCES `mydb`.`Paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadosTiquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadosTiquete` (
  `idEstadoTiquete` SMALLINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idEstadoTiquete`),
  UNIQUE INDEX `idEstadoTiquete_UNIQUE` (`idEstadoTiquete` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadosSolicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadosSolicitud` (
  `idEstadoSolicitud` SMALLINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idEstadoSolicitud`),
  UNIQUE INDEX `idEstadoSolicitud_UNIQUE` (`idEstadoSolicitud` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiposTiquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiposTiquete` (
  `idTipoTiquete` SMALLINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTipoTiquete`),
  UNIQUE INDEX `idTipoTiquete_UNIQUE` (`idTipoTiquete` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiquetesSoporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiquetesSoporte` (
  `idTiqueteSoporte` BIGINT NOT NULL AUTO_INCREMENT,
  `fechaApertura` DATETIME NOT NULL,
  `idTipoTiquete` SMALLINT NOT NULL,
  `idEstadoTiquete` SMALLINT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idTiqueteSoporte`),
  UNIQUE INDEX `idTiqueteSoporte_UNIQUE` (`idTiqueteSoporte` ASC),
  INDEX `fk_TiquetesSoporte_Empleados1_idx` (`idEmpleado` ASC),
  INDEX `fk_TiquetesSoporte_EstadosTiquete1_idx` (`idEstadoTiquete` ASC),
  INDEX `fk_TiquetesSoporte_TiposTiquete1_idx` (`idTipoTiquete` ASC),
  CONSTRAINT `fk_TiquetesSoporte_Empleados1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TiquetesSoporte_EstadosTiquete1`
    FOREIGN KEY (`idEstadoTiquete`)
    REFERENCES `mydb`.`EstadosTiquete` (`idEstadoTiquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TiquetesSoporte_TiposTiquete1`
    FOREIGN KEY (`idTipoTiquete`)
    REFERENCES `mydb`.`TiposTiquete` (`idTipoTiquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MediosRecepcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MediosRecepcion` (
  `idMedioRecepcion` SMALLINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idMedioRecepcion`),
  UNIQUE INDEX `idMedioRecepcion_UNIQUE` (`idMedioRecepcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `idComentario` BIGINT NOT NULL AUTO_INCREMENT,
  `idTiqueteSoporte` BIGINT NOT NULL,
  `detalle` VARCHAR(2000) NOT NULL,
  `fechaRecepcion` DATETIME NOT NULL,
  `idMedioRecepcion` SMALLINT NOT NULL,
  `nombreAutor` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idComentario`),
  UNIQUE INDEX `idComentario_UNIQUE` (`idComentario` ASC),
  INDEX `fk_Comentarios_TiquetesSoporte1_idx` (`idTiqueteSoporte` ASC),
  INDEX `fk_Comentarios_MediosRecepcion1_idx` (`idMedioRecepcion` ASC),
  CONSTRAINT `fk_Comentarios_TiquetesSoporte1`
    FOREIGN KEY (`idTiqueteSoporte`)
    REFERENCES `mydb`.`TiquetesSoporte` (`idTiqueteSoporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_MediosRecepcion1`
    FOREIGN KEY (`idMedioRecepcion`)
    REFERENCES `mydb`.`MediosRecepcion` (`idMedioRecepcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GradosSeveridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GradosSeveridad` (
  `idGradoSeveridad` SMALLINT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idGradoSeveridad`),
  UNIQUE INDEX `idGradoSeveridad_UNIQUE` (`idGradoSeveridad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SolicitudesAmonestacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SolicitudesAmonestacion` (
  `idSolicitudAmonestacion` BIGINT NOT NULL AUTO_INCREMENT,
  `idGradoSeveridad` SMALLINT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `idEmpleadoResponsable` INT NOT NULL,
  `idComentario` BIGINT NOT NULL,
  `idEstadoSolicitud` SMALLINT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`idSolicitudAmonestacion`),
  UNIQUE INDEX `idSolicitudAmonestacion_UNIQUE` (`idSolicitudAmonestacion` ASC),
  INDEX `fk_SolicitudesAmonestacion_EstadosSolicitud1_idx` (`idEstadoSolicitud` ASC),
  INDEX `fk_SolicitudesAmonestacion_Comentarios1_idx` (`idComentario` ASC),
  INDEX `fk_SolicitudesAmonestacion_GradosSeveridad1_idx` (`idGradoSeveridad` ASC),
  INDEX `fk_SolicitudesAmonestacion_Empleados1_idx` (`idEmpleado` ASC),
  INDEX `fk_SolicitudesAmonestacion_Empleados2_idx` (`idEmpleadoResponsable` ASC),
  CONSTRAINT `fk_SolicitudesAmonestacion_EstadosSolicitud1`
    FOREIGN KEY (`idEstadoSolicitud`)
    REFERENCES `mydb`.`EstadosSolicitud` (`idEstadoSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesAmonestacion_Comentarios1`
    FOREIGN KEY (`idComentario`)
    REFERENCES `mydb`.`Comentarios` (`idComentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesAmonestacion_GradosSeveridad1`
    FOREIGN KEY (`idGradoSeveridad`)
    REFERENCES `mydb`.`GradosSeveridad` (`idGradoSeveridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesAmonestacion_EmpleadosAmonestado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SolicitudesAmonestacion_EmpleadosResponsable`
    FOREIGN KEY (`idEmpleadoResponsable`)
    REFERENCES `mydb`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
